vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        post_image:
            uri_prefix: /storage/uploads
            upload_destination: '%kernel.project_dir%/public/storage/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
